# @import ./variablesInit.http

###
GET /classes?p=1
###
GET /classes/019a7fcf-8076-7de6-a412-4bd19dab6757

###
POST /classes
Content-Type: application/json

{
  "id": "019a7fcf-8076-7de6-a412-4bd19dab6758",
  "name": "Class 6"
}
###
DELETE /classes/019a7fcf-8076-7de6-a412-4bd19dab6758