
# @import ./variablesInit.http
###
POST /student-logs
Content-Type: application/json

{
  "driverId": "019a7fcf-8076-7de6-a412-4bd19dab6759",
  "studentId": "HS-000002",
  "direction": "IN"
}
  
###

POST /student-logs/test
Content-Type: application/json

{
  "driverId": "019a7fcf-8076-7de6-a412-4bd19dab6759",
  "studentId": "HS-000002",
  "direction": "IN"
}
###
GET /drivers?l=5&s=l

###

GET /students/HS-000000

###

PUT /students/019a7fcf-8076-7de6-a412-4bd19dab6799
Content-Type: application/json

{
   "name": "Nguyễn Văn Nam",
    "phone": "036701673",
    "phoneParent": "0367016888",
    "classId": "019a7fcf-8076-7de6-a412-4bd19dab6758"
}

###

DELETE /students/019a7fcf-8076-7de6-a412-4bd19dab6799

###
