
# @import ./variablesInit.http
###
POST /students
Content-Type: application/json

{
  "id": "019a7fcf-8076-7de6-a412-4bd19dab6758",
  "name": "Lê trung Hậu",
  "phone": "036701672",
  "phoneParent": "0367016872",
  "classId": "019a7fcf-8076-7de6-a412-4bd19dab6758"
}


###

# Step 2: Create a new Student in the class created above.
# @name createStudent
POST /students/bulk
Content-Type: application/json

[
  {
    "id": "019a7fcf-8076-7de6-a412-4bd19dab6758",
    "name": "Lê trung Hậu",
    "phone": "036701672",
    "phoneParent": "0367016872",
    "classId": "019a7fcf-8076-7de6-a412-4bd19dab6758"
  },
  {
    "id": "019a7fcf-8076-7de6-a412-4bd19dab6799",
    "name": "Nguyễn Văn Nam",
    "phone": "036701673",
    "phoneParent": "0367016888",
    "classId": "019a7fcf-8076-7de6-a412-4bd19dab6758"
  }
]

###

GET /students?l=5

###

GET /students/HS-000000

###

PUT /students/019a7fcf-8076-7de6-a412-4bd19dab6799
Content-Type: application/json

{
   "name": "Nguyễn Văn Nam",
    "phone": "036701673",
    "phoneParent": "0367016888",
    "classId": "019a7fcf-8076-7de6-a412-4bd19dab6758"
}

###

DELETE /students/019a7fcf-8076-7de6-a412-4bd19dab6799

###
